# https://hub.docker.com/_/microsoft-dotnet-core
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

# copy csproj
COPY ./src/RoomTempDashboard.csproj .
# copy everything else and build app
COPY ./src/ .
RUN dotnet publish -c Release -o out -r linux-arm --self-contained false

# final stage/image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim-arm32v7
WORKDIR /app
COPY --from=build /app/out ./

CMD ["dotnet", "RoomTempDashboard.dll"]