name: Docker Image CI

on:
  push:
    branches:
      - master
    #tags:
    #- '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Push to Docker Hub
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: seanonet/roomtempdashboard
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: contains(github.ref, 'refs/tags/v')
      with:
        tagging: true

